"use client";
import { api } from "~/trpc/react";
import { authClient } from "~/server/better-auth/client";

export default function AdminPage() {
  const { data: session } = authClient.useSession();
  // const {
  //   data: mostRecentApp,
  //   isLoading: mostRecentAppLoading,
  //   isError: mostRecentAppError,
  // } = api.apps.getLatest.useQuery();
  return (
    <div>
      <h1>Welcome back, {session?.user?.name}</h1>
      <p className="text-muted-foreground">
        View all statistics and reports generated by the system.
      </p>
    </div>
  );
}
