"use client";
import { api } from "~/trpc/react";
import { authClient } from "~/server/better-auth/client";
import { useState, useEffect } from "react";
import { SendIcon } from "lucide-react";
import { Button } from "~/components/ui/button";

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import {
  CartesianGrid,
  Line,
  PieChart,
  Pie,
  LineChart,
  Cell,
  XAxis,
  YAxis,
  BarChart,
  Bar,
} from "recharts";
import type { ChartConfig } from "~/components/ui/chart";
import {
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
} from "~/components/ui/chart";
import {
  getHourlyTraffic,
  getAppsByDentist,
  getServiceDistributionData,
} from "~/lib/summaries";
import { Book, BookUp, BookUser, UsersIcon, Wrench } from "lucide-react";
import { toast } from "sonner";
const SERVICES = [
  {
    id: 1,
    title: "General Cleaning",
    description:
      "Routine clinical check-ups, digital X-rays, deep cleanings, and protective fillings to maintain optimal long-term oral hygiene.",
    completionTime: "1 hour",
  },
  {
    id: 2,
    title: "Root Canal",
    description:
      "Specialized micro-treatments to eliminate internal tooth infections, relieve persistent throbbing pain, and save the natural tooth from extraction.",
    completionTime: "1 hour 30 mins",
  },
  {
    id: 3,
    title: "Wisdom Tooth Removal",
    description:
      "Advanced surgical removal of damaged, decayed, or deeply trapped impacted wisdom teeth to prevent gum infections and protect neighboring teeth.",
    completionTime: "2 hours",
  },
  {
    id: 4,
    title: "Dentures",
    description:
      "Premium custom-fitted full or partial dental prosthetics designed to restore natural speech, chewing function, and a complete smile after tooth loss.",
    completionTime: "2 hours 30 mins",
  },
];

const unifiedConfig = {
  appointments: {
    label: "Visits",
    color: "#69d2cb",
  },
  volume: {
    label: "Share",
  },
} satisfies ChartConfig;
export default function AdminPage() {
  const { data: session } = authClient.useSession();

  const { data: userCount, isLoading: userLoading } =
    api.users.getCount.useQuery();
  const { data: dentistCount, isLoading: dentistLoading } =
    api.dentists.getCount.useQuery();
  const { data: serviceCount, isLoading: serviceLoading } =
    api.services.getCount.useQuery();
  const {
    data: apps,
    isLoading: appsLoading,
    isError: appsError,
  } = api.apps.getAllForSummary.useQuery(
    {
      limit: 100,
    },
    { staleTime: 60 * 1000 },
  );

  const trafficData = getHourlyTraffic(apps?.data);
  const dentistData = getAppsByDentist(apps?.data);
  const serviceData = getServiceDistributionData(apps?.data);

  const sendEmail = api.email.sendGreeting.useMutation({
    onSuccess: () => {
      toast.success("Email sent successfully");
    },
    onError: () => {
      toast.error("Failed to send email");
    },
  });

  return (
    <div>
      <h1>Welcome back, {session?.user?.name}</h1>
      <p className="text-muted-foreground">
        View all statistics and reports generated by the system.
      </p>

      <div className="flex items-center justify-between">
        <div className=" w-full grid grid-cols-2 gap-4">
          <div className="bg-muted p-6 rounded-lg">
            <p className="text-muted-foreground text-xs flex gap-2 items-center">
              <Book size={12} /> Appointments
            </p>
            <h1 className="text-3xl">{apps?.data?.length}</h1>
          </div>
          <div className="bg-muted p-6 rounded-lg">
            <p className="text-muted-foreground text-xs flex gap-2 items-center">
              <UsersIcon size={12} /> Users
            </p>
            <h1 className="text-3xl ">{userCount ?? ""}</h1>
          </div>
          <div className="bg-muted p-6 rounded-lg">
            <p className="text-muted-foreground text-xs flex gap-2 items-center">
              <BookUser size={12} /> Dentists
            </p>
            <h1 className="text-3xl ">{dentistCount ?? ""}</h1>
          </div>{" "}
          <div className="bg-muted p-6 rounded-lg">
            <p className="text-muted-foreground text-xs flex gap-2 items-center">
              <Wrench size={12} /> Services
            </p>
            <h1 className="text-3xl ">{serviceCount ?? ""}</h1>
          </div>
        </div>
        <div className="w-full space-y-6 p-2 md:p-6">
          {/* Right 1-Column Block: The Treatment Distribution Pie/Donut Chart */}
          <Card className="flex flex-col justify-between shadow-none bg-muted p-3 rounded-lg lg:col-span-1">
            <CardHeader className="pb-0">
              <CardTitle className="">
                Services
                <p className="text-muted-foreground text-xs ">
                  Appointments by services
                </p>
              </CardTitle>
            </CardHeader>
            <CardContent className="pb-4 flex-1 flex items-center justify-center">
              <ChartContainer
                config={unifiedConfig}
                className="w-full aspect-square max-h-[110px]"
              >
                <PieChart>
                  <ChartTooltip
                    cursor={false}
                    content={<ChartTooltipContent hideLabel />}
                  />
                  <Pie
                    data={serviceData}
                    dataKey="volume"
                    nameKey="service"
                    innerRadius={38}
                    outerRadius={55}
                    strokeWidth={3}
                  >
                    {serviceData?.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.fill} />
                    ))}
                  </Pie>
                </PieChart>
              </ChartContainer>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* =========================================================================
                LOWER SECTION: 2 Equal Width Graphs (Hourly Traffic Left vs Dentist Activity Right)
                ========================================================================= */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Equal Graph 1: Hourly Patient Traffic (Bar Chart) */}
        <Card className="shadow-none bg-muted rounded-lg h-56 ">
          <CardHeader>
            <CardTitle className="">
              Hourly Patient Traffic
              <p className="text-muted-foreground text-xs ">
                Appointments by hour
              </p>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ChartContainer
              config={unifiedConfig}
              className="w-full max-h-[130px]"
            >
              <BarChart accessibilityLayer data={trafficData}>
                <CartesianGrid vertical={false} className="stroke-muted" />

                <XAxis
                  dataKey="timeSlot"
                  tickLine={false}
                  tickMargin={10}
                  axisLine={false}
                  className="text-xs"
                />
                <YAxis tickLine={false} axisLine={false} className="text-xs" />
                <ChartTooltip content={<ChartTooltipContent />} />
                <Bar
                  dataKey="appointments"
                  fill="#69d2cb"
                  radius={[4, 4, 0, 0]}
                />
              </BarChart>
            </ChartContainer>
          </CardContent>
        </Card>

        {/* Equal Graph 2: Dentist Activity Metrics (Line Chart) */}
        <Card className="rounded-lg shadow-none bg-muted p-3">
          <CardHeader>
            <CardTitle className="">
              Dentist Activity
              <p className="text-muted-foreground text-xs ">
                Appointments by dentist
              </p>
            </CardTitle>
            <CardDescription className="text-xs"></CardDescription>
          </CardHeader>
          <CardContent>
            <ChartContainer
              config={unifiedConfig}
              className="max-h-[130px] w-full"
            >
              <LineChart accessibilityLayer data={dentistData}>
                <CartesianGrid
                  vertical={false}
                  className="stroke-primary stroke-2"
                />
                <XAxis
                  dataKey="dentist"
                  tickLine={false}
                  axisLine={false}
                  tickMargin={10}
                  className="text-xs"
                />
                <YAxis tickLine={false} axisLine={false} className="text-xs" />
                <ChartTooltip
                  cursor={false}
                  content={<ChartTooltipContent />}
                />
                <Line
                  dataKey="appointments"
                  stroke="#69d2cb"
                  strokeWidth={2.5}
                  dot={{ fill: "#69d2cb", r: 4 }}
                  activeDot={{ r: 3 }}
                />
              </LineChart>
            </ChartContainer>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
